### ISSUE TITLE
It doesn't catch change object type

### ISSUE THREAD

**Issue by minicuper** [Tixit/odiff#1]
``` coffee
odiff = require 'odiff'

a = {}
b = []

diff = odiff(a,b)
console.log diff
# returns [] 
```

**Comment by fresheneesz** [comment]
Thanks for the note. Would you be willing to create a pull request for this?

**Comment by katywings** [comment]
I maybe need this so I could look into it :), are you already working on it @fresheneesz ?

**Comment by fresheneesz** [comment]
I'm not, so feel free to submit a pull request! Let me know of you have any questions.

**Comment by katywings** [comment]
Thx for the feedback, keep in mind that I first need to check, if this algorithm even works for my usecase. If it does, I will look into it to fix the array<>object comparison

**Comment by fresheneesz** [comment]
Ok I finally updated to support this.
