### ISSUE TITLE
`index` for `rm` appears to show _last_ index removed, not the first

### ISSUE THREAD

**Issue by justinanastos** [Tixit/odiff#3]
I found this while trying to get the previous values that were set to show an actually `+`/`-` diff.

```
const originalArray = ['a', 'b', 'c', 'd', 'e'];
const newArray = ['a', 'e'];
const diff = odiff(originalArray, newArray);
```

Will return:

```js
[
  {
    "type": "rm",
    "path": [],
    "index": 3,
    "num": 3
  }
]
```

`num` is correct, `3` elements were removed. `index` is the _last_ index that was removed; `d` in this case. I would expect `index` to be `1`, the first element removed.

If `index` was `1`, then it's trivial to get the original elements removed:

```js
const elementsRemoved = originalArray.slice(diff.index, diff.index + diff.num);
```

**Comment by fresheneesz** [comment]
Hmm, definitely not what I intended. Do you think you could submit a pull request fix?

**Comment by kevinludwig** [comment]
Would it be sufficient to simply change the `rm` method (here: https://github.com/Tixit/odiff/blob/master/odiff.js#L120) to set `index: index - count + 1`?

**Comment by kevinludwig** [comment]
https://github.com/Tixit/odiff/pull/4

**Comment by fresheneesz** [comment]
Thanks for the pull request! Yeah, good point about the version. I'll bump it a whole version.

**Comment by fresheneesz** [comment]
Published under v1.0.0

**Comment by cajurabi** [comment]
@fresheneesz is this closed?  I routinely review open issues list before deciding to use a package, and I believe your open issues, should probably be closed.  Am I correct?  Or are the open issues still issues for the package?

**Comment by fresheneesz** [comment]
Ah yes, this should be closed
